### ISSUE TITLE
Cannot run a second time the entire batch jobs

### ISSUE THREAD

**Issue by almex** [almex/Raildelays#6]
Exception in thread "main" org.springframework.batch.core.repository.JobInstanceAlreadyCompleteException: A job instance already exists and is complete for para                                             meters={output.file.path=file:./output.dat, station.a.name=Liège-Guillemins, dat                                             e=1404856800000, excel.input.template=resources/template.xls, station.b.name=Bru                                             ssels (Bruxelles)-Central, excel.output.path=/diskstation/NetDrive/999 - Divers/                                             SNCB/retard_sncb.xls}.  If you want to run this job again, change the parameters                                             .
        at org.springframework.batch.core.repository.support.SimpleJobRepository.createJobExecution(SimpleJobRepository.java:126)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:98)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:262)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.batch.core.repository.support.AbstractJobRepositoryFactoryBean$1.invoke(AbstractJobRepositoryFactoryBean.java:172)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
        at com.sun.proxy.$Proxy41.createJobExecution(Unknown Source)
        at org.springframework.batch.core.launch.support.SimpleJobLauncher.run(SimpleJobLauncher.java:125)
        at be.raildelays.batch.service.impl.BatchStartAndRecoveryServiceImpl.restart(BatchStartAndRecoveryServiceImpl.java:249)
        at be.raildelays.batch.service.impl.BatchStartAndRecoveryServiceImpl.restartFailedJobs(BatchStartAndRecoveryServiceImpl.java:166)
        at be.raildelays.batch.service.impl.BatchStartAndRecoveryServiceImpl.markInconsistentJobsAsFailed(BatchStartAndRecoveryServiceImpl.java:92)
        at be.raildelays.batch.Bootstrap.main(Bootstrap.java:87)

**Comment by ghost** [comment]
Can someone please guide here: https://stackoverflow.com/questions/53684865/spring-batch-run-fine-for-1st-run-but-for-2nd-and-so-on-runs-it-keeps-failin ?
